name: lobe-chat-database
services:
  network-service:
    image: alpine
    container_name: lobe-network
    ports:
      - '${RUSTFS_PORT}:9000' # RustFS API
      - '${RUSTFS_CONSOLE_PORT}:9001' # RustFS Console
      - '8080:8080' # Zitadel Console
      - '3210:3210' # LobeChat
    command: tail -f /dev/null
    networks:
      - lobe-network

  postgresql:
    image: pgvector/pgvector:pg16
    container_name: lobe-postgres
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - './data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_DB=lobechat'
      - 'POSTGRES_PASSWORD=uWNZugjBqixf8dxC'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - lobe-network

  rustfs:
    image: rustfs/rustfs:latest
    container_name: lobe-rustfs
    network_mode: 'service:network-service'
    volumes:
      - './rustfs-data:/data'
    environment:
      - 'RUSTFS_CONSOLE_ENABLE=true'
      - 'RUSTFS_ACCESS_KEY=${RUSTFS_ROOT_ACCESS_KEY}'
      - 'RUSTFS_SECRET_KEY=${RUSTFS_ROOT_SECRET_KEY}'
    restart: always
    env_file:
      - .env


  zitadel:
    restart: 'always'
    image: 'ghcr.io/zitadel/zitadel:latest'
    container_name: lobe-zitadel
    network_mode: 'service:network-service'
    command: start-from-init --config /zitadel-config.yaml --steps /zitadel-init-steps.yaml --masterkey "cft3Tekr/rQBOqwoQSCPoncA9BHbn7QJ" --tlsMode disabled #MasterkeyNeedsToHave32Characters
    volumes:
      - ./zitadel-config.yaml:/zitadel-config.yaml:ro
      - ./zitadel-init-steps.yaml:/zitadel-init-steps.yaml:ro
    depends_on:
      postgresql:
        condition: service_healthy

  lobe:
    image: lobehub/lobe-chat-database
    container_name: lobe-chat
    network_mode: 'service:network-service'
    depends_on:
      postgresql:
        condition: service_healthy
      network-service:
        condition: service_started
      rustfs:
        condition: service_started
      zitadel:
        condition: service_started
    env_file:
      - .env
    restart: always

volumes:
  data:
    driver: local
  rustfs_data:
    driver: local
networks:
  lobe-network:
    driver: bridge
